openapi: '3.0.3'

info:
  title: IDentigraF Internal Authentication API
  description: Authentication and Tracking Internal API for [IDentigraF](https://neuro.identigraf.center/). **This API is not exposed publicly**.
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /
    description: This server

components:
  responses:
    trackUpload:
      description: Successful response
      content:
        application/json:
          example:
            success: true
            response:
              credits: 2
              whitelisted: false
          schema:
            type: object
            properties:
              success:
                $ref: "./generic-responses.yaml#/components/schemas/operationSucceeded"
              response:
                type: object
                properties:
                  credits:
                    description: Number of credits remaining
                    type: number
                  whitelisted:
                    description: Whether the user is whitelisted
                    type: boolean
                required:
                  - credits
                  - whitelisted
            required:
              - success
              - response

    checkCredits:
      description: Successful response
      content:
        application/json:
          example:
            success: true
            credits: 5
          schema:
            type: object
            properties:
              success:
                $ref: "./generic-responses.yaml#/components/schemas/operationSucceeded"
              credits:
                description: Number of remaining credits
                type: number
                format: int32

paths:
  /session:
    post:
      summary: Start session
      tags:
        - IDentigraF Internal Authentication API
      security: []
      operationId: startSession
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  description: External User ID
                  type: string
                phone:
                  description: Phone number
                  type: string
                  # pattern: "^\\+380[0-9]{9}$"
              required:
                - uid
                - phone
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "200":
          description: Successful response, session has been started
          content:
            application/json:
              examples:
                success:
                  $ref: "./identigraf-auth-common.yaml#/components/examples/startSession"
              schema:
                $ref: "./identigraf-auth-common.yaml#/components/schemas/startSessionResponse"

  /track:
    post:
      summary: Track search or compare operation
      tags:
        - IDentigraF Internal Tracking API
      security: []
      operationId: trackOperation
      requestBody:
        required: true
        content:
          application/json:
            example:
              type: search
              guid: "00000000-0000-0000-0000-000000000000"
              phone: "+380680000000"
              ips:
                - '78.30.235.66'
              dt: 1593640625
            schema:
              type: object
              properties:
                type:
                  description: Operation to track
                  type: string
                  enum: [search, compare]
                guid:
                  description: FaceX GUID
                  type: string
                  pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
                phone:
                  description: Phone number
                  type: string
                  # pattern: "^\\+[0-9]{7,16}$"
                ips:
                  description: IP addresses
                  type: array
                  minItems: 1
                  items:
                    type: string
                    oneOf:
                      - format: ipv4
                      - format: ipv6
                dt:
                  description: Timestamp (number of seconds since the Epoch)
                  type: number
                  minimum: 1392854400
              required:
                - type
                - guid
                - phone
                - ips
                - dt
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "200":
          $ref: "#/components/responses/trackUpload"

  /credits/{phone}:
    get:
      summary: Get remaining credits by phone
      description: This is an internal API endpoint, it cannot be invoked from the outside.
      tags:
        - IDentigraF Internal Authentication API
      security: []
      operationId: getRemainingCredits
      parameters:
        - name: phone
          description: Phone number
          example: "380680000000"
          in: path
          required: true
          schema:
            description: Phone number
            type: string
            # pattern: "^380[0-9]{9}$"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "200":
          $ref: "#/components/responses/checkCredits"

  /checkphone:
    post:
      summary: Check phone number
      tags:
        - IDentigraF Internal Authentication API
      security: []
      operationId: checkPhone
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/checkPhone"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "429":
          description: Too Many Requests
          content:
            application/json:
              example:
                success: false
                status: 429
                code: OUT_OF_CREDITS
                message: You have run out of credits
              schema:
                type: object
                properties:
                  success:
                    $ref: "./generic-responses.yaml#/components/schemas/operationFailed"
                  status:
                    description: HTTP status code
                    type: number
                    enum: [429]
                  code:
                    description: Error code
                    type: string
                    enum: [OUT_OF_CREDITS]
                  message:
                    description: Error description
                    type: string
                required:
                  - success
                  - status
                  - code
                  - message
          headers:
            X-RateLimit-Limit:
              description: The number of credits in the current period
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: The number of remaining credits in the current period
              schema:
                type: integer
            X-RateLimit-Reset:
              description: The number of seconds left in the current period
              schema:
                type: integer

        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/checkPhoneSucceeded"

  /users/{id}:
    get:
      summary: Get user by ID.
      tags:
        - IDentigraF Internal User API
      security: []
      operationId: getUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
    patch:
      summary: Update user by ID.
      tags:
        - IDentigraF Internal User API
      security: []
      operationId: patchUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/patchUser"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "400":
          $ref: "./identigraf-auth-common.yaml#/components/responses/patchBadRequest"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
    put:
      summary: Update user by ID.
      tags:
        - IDentigraF Internal User API
      security: []
      operationId: updateUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/updateUser"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

  /users:
    get:
      summary: Get user list.
      tags:
        - IDentigraF Internal User API
      security: []
      operationId: searchUsers
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchLogin"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchComment"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchUserSort"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/sortDirection"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/queryOffset"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/queryLimit"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/searchUsers"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
