openapi: '3.0.3'

info:
  title: IDentigraF OID Decoder API
  description: |
    API for IDentigraF's Decoder Microservice: parses encoded object IDs, and retrieves some information about them
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /identigraf-decoder/v1
    description: This server
  - url: https://api2.myrotvorets.center/identigraf-decoder/v1
    description: Production server

paths:
  /decode:
    post:
      summary: Decode object names
      tags:
        - IDentigraF Decoder API
      security: []
      operationId: decode
      requestBody:
        required: true
        content:
          application/json:
            examples:
              decodeRequestBody:
                $ref: "./identigraf-decoder-common.yaml#/components/examples/decodeRequestBody"
            schema:
              $ref: "./identigraf-decoder-common.yaml#/components/schemas/decodeRequestBody"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "403":
          $ref: "./generic-responses.yaml#/components/responses/forbidden"

        "429":
          $ref: "./generic-responses.yaml#/components/responses/rate-limit"

        "200":
          description: Successful response
          content:
            application/json:
              examples:
                success:
                  $ref: "./identigraf-decoder-common.yaml#/components/examples/decodeResponseBody"
                nothing-decoded:
                  $ref: "./identigraf-decoder-common.yaml#/components/examples/decodeResponseBodyEmpty"
              schema:
                $ref: "./identigraf-decoder-common.yaml#/components/schemas/decodeResponseBody"
