openapi: '3.0.3'

info:
  title: IDentigraF Authentication API
  description: Authentication and Tracking API for [IDentigraF](https://neuro.identigraf.center/)
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /identigraf-auth/v2
    description: This server

components:
  securitySchemes:
    myrotvorets-jwt:
      description: Myrotvorets JWT
      bearerFormat: JWT
      type: http
      scheme: bearer

paths:
  /login:
    post:
      summary: Log the user in
      tags:
        - IDentigraF Authentication API
      security:
        - myrotvorets-jwt: []
      operationId: login
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"

        "429":
          $ref: "./generic-responses.yaml#/components/responses/rate-limit"

        "200":
          description: Successful response, session has been started
          content:
            application/json:
              examples:
                success:
                  $ref: "./identigraf-auth-common.yaml#/components/examples/startSession"
              schema:
                $ref: "./identigraf-auth-common.yaml#/components/schemas/startSessionResponse"

  /checkphone:
    post:
      summary: Check phone number
      description: |
        If the API returns `429` response, the `code` can be one of the following:
          * `OUT_OF_CREDITS`: the user has run out of credits
          * `RATE_LIMIT_EXCEEDED`: please slow down, you are sending too many requests
      tags:
        - IDentigraF Authentication API
      security: []
      operationId: checkPhone
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/checkPhone"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

        "403":
          $ref: "./generic-responses.yaml#/components/responses/forbidden"

        "429":
          $ref: "./generic-responses.yaml#/components/responses/rate-limit"

        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/checkPhoneSucceeded"

  /users/{id}:
    get:
      summary: Get user by ID.
      tags:
        - IDentigraF User API
      security:
        - myrotvorets-jwt: []
      operationId: getUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
    patch:
      summary: Update user by ID.
      tags:
        - IDentigraF User API
      security:
        - myrotvorets-jwt: []
      operationId: patchUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/patchUser"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "400":
          $ref: "./identigraf-auth-common.yaml#/components/responses/patchBadRequest"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
    put:
      summary: Update user by ID.
      tags:
        - IDentigraF User API
      security:
        - myrotvorets-jwt: []
      operationId: updateUserById
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/userID"
      requestBody:
        $ref: "./identigraf-auth-common.yaml#/components/requestBodies/updateUser"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/getUserById"
        "404":
          $ref: "./identigraf-auth-common.yaml#/components/responses/userNotFound"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

  /users:
    get:
      summary: Get user list.
      tags:
        - IDentigraF User API
      security:
        - myrotvorets-jwt: []
      operationId: searchUsers
      parameters:
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchLogin"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchComment"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/searchUserSort"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/sortDirection"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/queryOffset"
        - $ref: "./identigraf-auth-common.yaml#/components/parameters/queryLimit"
      responses:
        "200":
          $ref: "./identigraf-auth-common.yaml#/components/responses/searchUsers"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
