openapi: '3.0.3'

info:
  title: IDentigraF Uploader API
  description: "API for IDentigraF's Uploader Microservice"
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /
    description: Microservice server URL

paths:
  /compare/{guid}:
    post:
      summary: Save photos for comparison
      tags:
        - IDentigraF Uploader Internal API
      security: []
      operationId: saveCompare
      parameters:
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/guid"
      requestBody:
        $ref: "./identigraf-uploader-common.yaml#/components/requestBodies/saveCompareRequest"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "200":
          $ref: "./identigraf-uploader-common.yaml#/components/responses/saveSuccessfulResponse"

  /search/{guid}:
    post:
      summary: Save the photo for search
      tags:
        - IDentigraF Uploader Internal API
      security: []
      operationId: saveSearch
      parameters:
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/guid"
      requestBody:
        $ref: "./identigraf-uploader-common.yaml#/components/requestBodies/saveSearchRequest"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "200":
          $ref: "./identigraf-uploader-common.yaml#/components/responses/saveSuccessfulResponse"

  /get/{guid}:
    get:
      summary: Retrieve a photo by search operation GUID
      tags:
        - IDentigraF Uploader API
      security: []
      operationId: getSearchPhoto
      parameters:
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/guid"
      responses:
        "200":
          $ref: "./identigraf-uploader-common.yaml#/components/responses/getSuccessfulResponse"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

  /get/{guid}/{number}:
    get:
      summary: Retrieve a photo by the compare operation GUID and photo number
      tags:
        - IDentigraF Uploader API
      security: []
      operationId: getComparePhoto
      parameters:
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/guid"
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/number"
      responses:
        "200":
          $ref: "./identigraf-uploader-common.yaml#/components/responses/getSuccessfulResponse"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"

  /count/{guid}:
    get:
      summary: Retrieve the number of photos for the compare operation identified by GUID
      tags:
        - IDentigraF Uploader API
      security: []
      operationId: countPhotos
      parameters:
        - $ref: "./identigraf-uploader-common.yaml#/components/parameters/guid"
      responses:
        "200":
          $ref: "./identigraf-uploader-common.yaml#/components/responses/countSuccessfulResponse"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
