openapi: "3.0.3"

info:
  title: IP Geolocation API
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /ipgeo/v2
    description: This server
  - url: https://api.myrotvorets.center/ipgeo/v2
    description: Production server

paths:
  /country:
    get:
      summary: Get country information for the connecting IP.
      tags:
        - IP Geolocation API
      security: []
      operationId: getCountry
      responses:
        "200":
          description: Successful response.
          content:
            "application/json":
              examples:
                successfulResponse:
                  $ref: "./ipgeo-common.yaml#/components/examples/countryResponseBody"
              schema:
                $ref: "./ipgeo-common.yaml#/components/schemas/countryResponseBody"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "429":
          $ref: "./generic-responses.yaml#/components/responses/rate-limit"

  /geolocate/{ip}:
    get:
      summary: Get geolocation information about the IP address.
      tags:
        - IP Geolocation API
      security: []
      operationId: geolocate
      parameters:
        - $ref: "./ipgeo-common.yaml#/components/parameters/ip"
      responses:
        "200":
          description: Successful response.
          content:
            "application/json":
              examples:
                successfulResponse:
                  $ref: "./ipgeo-common.yaml#/components/examples/geolocateResponseBody"
              schema:
                $ref: "./ipgeo-common.yaml#/components/schemas/geolocateResponseBody"
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "429":
          $ref: "./generic-responses.yaml#/components/responses/rate-limit"
