openapi: "3.0.3"

info:
  title: IP Geolocation API
  version: 2.0.0
  contact:
    email: support@myrotvorets.center

servers:
  - url: /
    description: This server

paths:
  /country:
    get:
      description: Get country information for the connecting IP.
      tags:
        - IP Geolocation API
      responses:
        "200":
          description: Successful response.
          content:
            "application/json":
              examples:
                successfulResponse:
                  $ref: "ipgeo-common.yaml#/components/examples/countryResponseBody"
              schema:
                $ref: "ipgeo-common.yaml#/components/schemas/countryResponseBody"
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"

  /geolocate/{ip}:
    get:
      description: Get geolocation information about the IP address.
      tags:
        - IP Geolocation API
      parameters:
        - $ref: "ipgeo-common.yaml#/components/parameters/ip"
      responses:
        "200":
          description: Successful response.
          content:
            "application/json":
              examples:
                successfulResponse:
                  $ref: "ipgeo-common.yaml#/components/examples/geolocateResponseBody"
              schema:
                $ref: "ipgeo-common.yaml#/components/schemas/geolocateResponseBody"
        default:
          $ref: "generic-responses.yaml#/components/responses/error_generic"
