openapi: "3.0.3"

info:
  title: Photos Microservice
  description: FaceX Photo API. The microservice is designed to be used by FaceX-related infrastructure
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: support@myrotvorets.center

servers:
  - url: /photos/v2
    description: This server
  - url: https://api2.myrotvorets.center/photos/v2
    description: Production server

components:
  securitySchemes:
    photos-auth:
      description: Short-lived JSON Web Token.
      type: http
      scheme: bearer

paths:
  /suspects/{after}/{count}:
    get:
      summary: Get the list of suspects IDs with photos
      description: |
        Retrieves up to `:count` IDs of suspects with photos; IDs of the suspects are in the ascending order.
        Only IDs greater than `:after` are returned
      tags:
        - Photos
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/after"
        - $ref: "./photos-common.yaml#/components/parameters/count"
      security:
        - photos-auth: []
      operationId: getSuspectsIDs
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response; returns an array (possibly empty) of suspects IDs
          content:
            "application/json":
              examples:
                getSuspectsIDs:
                  $ref: "./photos-common.yaml#/components/examples/getSuspectsIDs"
              schema:
                $ref: "./photos-common.yaml#/components/schemas/getSuspectsIDsResponse"

  /suspects/{id}:
    get:
      summary: Get the list of suspect's photos
      description: Retrieves the list of suspect's photos (only `image/*` attachments are returned)
      tags:
        - Photos
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/cid"
      security:
        - photos-auth: []
      operationId: getSuspectPhotos
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response
          content:
            "application/json":
              examples:
                getSuspectPhotos:
                  $ref: "./photos-common.yaml#/components/examples/getSuspectPhotos"
              schema:
                $ref: "./photos-common.yaml#/components/schemas/getSuspectPhotosResponse"

  /{id}:
    get:
      summary: Get photo by ID
      description: Retrieves a photo by ID. Returns a 404 error if the photo cannot be found, or 502 if the photo cannot be retrieved.
      tags:
        - Photos
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/att_id"
      security:
        - photos-auth: []
      operationId: getPhotoByID
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response
          content:
            "image/*":
              schema:
                type: string
                format: binary

  /{id}/facex:
    get:
      summary: Get photo by ID in the format suitable for FaceX
      description: |
        Retrieves a photo by ID as a non-interlaced JPEG with 4:2:0 chroma subsampling.
        Returns a 404 error if the photo is not found, contains errors, or cannot be converted into the format suitable for FaceX.
        Returns a 502 if there is an error retrieving the photo.
      tags:
        - Photos
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/att_id"
      security:
        - photos-auth: []
      operationId: getPhotoByIDForFaceX
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response
          content:
            "image/jpeg":
              schema:
                type: string
                format: binary

  /sync:
    get:
      summary: Get next entry to sync with FaceX
      description: |
        Retrieves an entry for the log of the changed photos. If the photo is to be added to FaceX,
        converts it into the suitable format.
      tags:
        - Photos
      security:
        - photos-auth: []
      operationId: getNextEntryToSync
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "./photos-common.yaml#/components/schemas/syncResponse"
        "204":
          description: No entries to sync

  /sync/{id}:
    put:
      summary: Set sync status for the given entry
      description: Marks the entry in the sync log as succeeded ot failed
      tags:
        - Photos
      security:
        - photos-auth: []
      operationId: setSyncStatus
      parameters:
        - $ref: 'photos-common.yaml#/components/parameters/sync_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'photos-common.yaml#/components/schemas/setSyncStatusRequest'
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "204":
          description: Status logged

  /sync/suspects/{after}/{count}:
    get:
      summary: Get the list of IDs of the suspects which need to be synced in FaceX
      description: |
        Retrieves up to `:count` IDs of the suspects; IDs of the suspects are in the ascending order.
        Only IDs greater than `:after` are returned
      tags:
        - Photos
      security:
        - photos-auth: []
      operationId: getSuspectsIDsToSync
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/after"
        - $ref: "./photos-common.yaml#/components/parameters/count"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "200":
          description: Successful response; returns an array (possibly empty) of suspects IDs
          content:
            "application/json":
              examples:
                getSuspectsIDs:
                  $ref: "./photos-common.yaml#/components/examples/getSuspectsIDs"
              schema:
                $ref: "./photos-common.yaml#/components/schemas/getSuspectsIDsResponse"

  /sync/suspects/{id}:
    delete:
      summary: Marks the suspect as synchronized with FaceX
      tags:
        - Photos
      security:
        - photos-auth: []
      operationId: markSuspectAsSynced
      parameters:
        - $ref: "./photos-common.yaml#/components/parameters/cid"
      responses:
        default:
          $ref: "./generic-responses.yaml#/components/responses/error_generic"
        "401":
          $ref: "./generic-responses.yaml#/components/responses/not-authorized"
        "502":
          $ref: "./generic-responses.yaml#/components/responses/bad-gateway"
        "204":
          description: Successful response

tags:
  - name: Photos
    description: FaceX Photo API
